title: Your awesome title
author: GitHub User
email: your-email@domain.com
theme: jekyll-theme-tactile
description: > My life is very interesting. # this means to ignore newlines until "baseurl:"
 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
